### ISSUE TITLE
Serverside Rendering?

### ISSUE THREAD

**Issue by gregghawes** [justinmahar/react-social-media-embed#7]
Is it possible to use this package with serverside rendering? I am getting an id mismatch using NextJS

**Comment by justinmahar** [comment]
I'm in the GatsbyJS camp myself, and SSR is at least working there. Any more info you can provide? I'd love to get support for both frameworks.

**Comment by blimpmason** [comment]
I'm also seeing mismatch warnings in Next.js:

```
Warning: Text content did not match. Server: "
        .rsme-spinner-1ff0c2d0-9a4b-4a11-aab3-b5230b7416aa {
          border: 6px solid rgba(0, 0, 0, 0.1);
          border-top: 6px solid #000000;
          border-radius: 50%;
          width: 18px;
          min-width: 18px;
          max-width: 18px;
          height: 18px;
          min-height: 18px;
          max-height: 18px;
          animation: rsme-spinner-1ff0c2d0-9a4b-4a11-aab3-b5230b7416aa-spin 1s linear infinite;
        }

        @keyframes rsme-spinner-1ff0c2d0-9a4b-4a11-aab3-b5230b7416aa-spin {
          0% {
            transform: rotate(0deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }  
      " Client: "
        .rsme-spinner-0b46c6db-1f0f-44ba-9d11-220b66c7dad5 {
          border: 6px solid rgba(0, 0, 0, 0.1);
          border-top: 6px solid #000000;
          border-radius: 50%;
          width: 18px;
          min-width: 18px;
          max-width: 18px;
          height: 18px;
          min-height: 18px;
          max-height: 18px;
          animation: rsme-spinner-0b46c6db-1f0f-44ba-9d11-220b66c7dad5-spin 1s linear infinite;
        }

        @keyframes rsme-spinner-0b46c6db-1f0f-44ba-9d11-220b66c7dad5-spin {
          0% {
            transform: rotate(0deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }  
      "
    at style
    at Spinner (webpack-internal:///./node_modules/react-social-media-embed/dist/components/placeholder/parts/Spinner.js:23:11)
    at div
    at div
    at a
    at div
    at PlaceholderEmbed (webpack-internal:///./node_modules/react-social-media-embed/dist/components/placeholder/PlaceholderEmbed.js:25:11)
    at TwitterTweetEmbed (webpack-internal:///./node_modules/react-twitter-embed/dist/index.modern.js:299:58)
    at div
    at TwitterEmbed (webpack-internal:///./node_modules/react-social-media-embed/dist/components/embeds/TwitterEmbed.js:48:11)
```
Let me know what other info would be helpful to debug this!

**Comment by nbilz** [comment]
Same here,

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

`Warning: Text content did not match. Server: "
        .rsme-spinner-419f1362-e745-4984-993c-873a580d1298 {
          border: 6px solid rgba(0, 0, 0, 0.1);
          border-top: 6px solid #000000;
          border-radius: 50%;
          width: 18px;
          min-width: 18px;
          max-width: 18px;
          height: 18px;
          min-height: 18px;
          max-height: 18px;
          animation: rsme-spinner-419f1362-e745-4984-993c-873a580d1298-spin 1s linear infinite;
        }

        @keyframes rsme-spinner-419f1362-e745-4984-993c-873a580d1298-spin {
          0% {
            transform: rotate(0deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }  
      " Client: "
        .rsme-spinner-7391b887-a02f-41f2-9e2d-a1ded7d35d81 {
          border: 6px solid rgba(0, 0, 0, 0.1);
          border-top: 6px solid #000000;
          border-radius: 50%;
          width: 18px;
          min-width: 18px;
          max-width: 18px;
          height: 18px;
          min-height: 18px;
          max-height: 18px;
          animation: rsme-spinner-7391b887-a02f-41f2-9e2d-a1ded7d35d81-spin 1s linear infinite;
        }

        @keyframes rsme-spinner-7391b887-a02f-41f2-9e2d-a1ded7d35d81-spin {
          0% {
            transform: rotate(0deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }  
      "
style
Spinner
div
div
a
div
PlaceholderEmbed
blockquote
div
InstagramEmbed
section
_classCallCheck
_classCallCheck
PureComponent
ReactDevOverlay
_classCallCheck
AppContainer`

**Comment by justinmahar** [comment]
Closing for now. Please reopen if the issue persists.

**Comment by fung-vin** [comment]
Hello,

Seems issue is still present when using the instagram embed? I'm also using the Twitter embed and do not get this error.

Thanks

```
next-dev.js?b74a:20 Warning: Prop `id` did not match. Server: "e52e0d5e-6009-4a1e-a42c-fbd40001166f" Client: "b05477e1-8ea5-4316-b788-3c6f83cc4eaa"
    at div
    at blockquote
    at div
    at InstagramEmbed (webpack-internal:///../../.yarn/__virtual__/react-social-media-embed-virtual-9e0b9d17bb/0/cache/react-social-media-embed-npm-2.3.4-a3f1d7d687-3e4c7f5b32.zip/node_modules/react-social-media-embed/dist/components/embeds/InstagramEmbed.js:62:11)
    at div
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Component (webpack-internal:///./components/content/content-schema-render/blockquote/index.tsx:150:27)
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ContentSchemaRender (webpack-internal:///./components/content/content-schema-render/index.tsx:125:20)
    at section
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ContentBody (webpack-internal:///./components/content/content-body/index.tsx:96:27)
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at GenericArticle (webpack-internal:///./components/article/article-render/generic-article/index.tsx:11:26)
    at Gallery (webpack-internal:///../../.yarn/__virtual__/react-photoswipe-gallery-virtual-853e3f501f/0/cache/react-photoswipe-gallery-npm-2.2.3-86d64e4935-4fd3ff1622.zip/node_modules/react-photoswipe-gallery/dist/gallery.js:49:3)
    at Gallery (webpack-internal:///./components/image-gallery/gallery.tsx:156:27)
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ImageGallery (webpack-internal:///./components/image-gallery/index.tsx:25:26)
    at ArticleImageGallery (webpack-internal:///./components/article/article-image-gallery/index.tsx:17:26)
    at InnerThemeProvider (webpack-internal:///../../.yarn/__virtual__/@mui-system-virtual-6e6758e2ea/0/cache/@mui-system-npm-5.11.7-dfbb6a04e7-00dbd8e7c6.zip/node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///../../.yarn/__virtual__/@mui-private-theming-virtual-bd08fac33b/0/cache/@mui-private-theming-npm-5.11.7-191c5b3c42-2ffcec8313.zip/node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///../../.yarn/__virtual__/@mui-system-virtual-6e6758e2ea/0/cache/@mui-system-npm-5.11.7-dfbb6a04e7-00dbd8e7c6.zip/node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at div
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ArticleRender (webpack-internal:///./components/article/article-render/index.tsx:103:26)
    at article
    at eval (webpack-internal:///../../.yarn/__virtual__/@emotion-react-virtual-5518eba2c0/0/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip/node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ArticlePage (webpack-internal:///./pages/article/index.page.tsx:155:32)
    at WiredComponent (webpack-internal:///../../.yarn/__virtual__/relay-nextjs-virtual-f445afa764/0/cache/relay-nextjs-npm-1.0.2-3f28710788-2bf6eb1f12.zip/node_modules/relay-nextjs/wired/component.js:61:33)
    at div
    at VisualElementHandler (webpack-internal:///../../.yarn/__virtual__/framer-motion-virtual-fe212daa13/0/cache/framer-motion-npm-9.0.1-9e4447cfee-e4e47bad60.zip/node_modules/framer-motion/dist/es/motion/utils/VisualElementHandler.mjs:8:1)
    at MotionComponent (webpack-internal:///../../.yarn/__virtual__/framer-motion-virtual-fe212daa13/0/cache/framer-motion-npm-9.0.1-9e4447cfee-e4e4
```

**Comment by semy** [comment]
Same error for me... :(

**Comment by iamalvisng** [comment]
With the latest version 2.3.5, this issue still persists.

**Comment by vip30** [comment]
I think it's because you're using generateUUID at here https://github.com/justinmahar/react-social-media-embed/blob/master/src/components/embeds/TikTokEmbed.tsx#L59C48-L59C48 which will cause the server side generated value is different when the page is in hydration stage

**Comment by dnsdrs** [comment]
The error still persist in my case (NextJS)

For those who might end up here with the same issue, here is what I did :

```jsx
"use client";

import { InstagramEmbed } from "react-social-media-embed";
import { useEffect, useState } from "react";

export function FixedInstagramEmbed({ children }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsClient(true);
    }
  }, []);

    return isClient ? (
        <InstagramEmbed url={children[0]} />
    ) : null;
}
```

This way, it only renders in the client and never in the server so there is no id missmatch.
